#+TITLE: CS 410 Final Project Proposal - Password Manager
#+AUTHOR: Sam Messina and Dan Jensen
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* Proposal

  For our project, we plan on creating a password manager. Password managers are used to create, store, retrieve, and update passwords for different services. They are useful for creating different passwords for different services without having to remember all of them. A good password manager should be both easy to use and secure. The application will be written in Python, and will feature a terminal-based user interface.

* Features

  Our password manager will be able to:

  1. Store user passwords
     1. User passwords will be encrypted before storage
  2. Update a specific service's password
  3. Remove a password from the directory
  4. Passwords will be protected by a "master password," which must be entered in order to access passwords for a given service.
  5. Passwords can be copied to a clipboard on command for easy use

* Potential Extensions

  Optional improvements include:

  1. Storage will take place locally, with the option for online upload
  2. Auto-fill online forms with a given password
  3. Implement the password encryption technique ourselves
